# 넘파이(Numpy: Numerical Python)

In [2]:
import numpy as np          # de facto standard

### 1. ndarray(Numpy N-Dimensional Array)

In [3]:
a = np.array([1,4,5,8], dtype=np.int32)     
a

array([1, 4, 5, 8], dtype=int32)

In [4]:
a.dtype         # int16, int32, int64, uint8, uint16, ...

dtype('int32')

In [5]:
a.shape         # tuple로 보여줌

(4,)

- Vector (1차원)

In [6]:
a = np.array([1,4,5,8])
a

array([1, 4, 5, 8])

- Matrix (2차원)

In [9]:
m = [[1,2,5,8], [2,3,4,9], [4,5,6,7]]
m = np.array(m)
m

array([[1, 2, 5, 8],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [11]:
m.shape, m.dtype

((3, 4), dtype('int64'))

- Tensor (3차원)

In [12]:
t = np.arange(24).reshape(2,3,4)
t

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
t.shape, t.dtype

((2, 3, 4), dtype('int64'))

In [15]:
a.ndim, m.ndim, t.ndim      # 차원

(1, 2, 3)

In [16]:
a.size, m.size, t.size      # 요소의 갯수

(4, 12, 24)

- dtype

In [17]:
np.array([1, 2.3, '4'])

array(['1', '2.3', '4'], dtype='<U32')

In [18]:
np.array([1, 2.3, '4'], dtype=np.float32)

array([1. , 2.3, 4. ], dtype=float32)

- reshape

In [19]:
t.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
m.reshape(2,2,3)

array([[[1, 2, 5],
        [8, 2, 3]],

       [[4, 9, 4],
        [5, 6, 7]]])

In [21]:
a.reshape(1,4)

array([[1, 4, 5, 8]])

In [22]:
a.reshape(4,1)

array([[1],
       [4],
       [5],
       [8]])

In [23]:
a.reshape(-1,1)

array([[1],
       [4],
       [5],
       [8]])

In [24]:
m.reshape(-1)

array([1, 2, 5, 8, 2, 3, 4, 9, 4, 5, 6, 7])

In [25]:
m.flatten()

array([1, 2, 5, 8, 2, 3, 4, 9, 4, 5, 6, 7])

### 2. Indexing & Slicing

In [26]:
a[0], a[-1]

(1, 8)

In [27]:
m

array([[1, 2, 5, 8],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [28]:
m[1][1], m[1,1]

(3, 3)